# Main configuration file for preprocessing

defaults:
  - preprocessing: default
  - _self_

data:
  raw_path: data/raw/raw.csv
  interim_path: data/interim/interim.parquet
  metadata_path: data/interim/interim_metadata.json

save: true
