# Main configuration file
defaults:
  - experiment: experiment_with_feature_engineering
  - _self_
save: true
run_name: "iterative_preprocessing"
name: "house-pricing"

data:
  repository_type: filesystem
  raw_path: data/raw/raw.csv
  interim_path: data/interim/interim.parquet
  metadata_path: data/interim/interim_metadata.json
